Import('AVR_ENV')
env = AVR_ENV

env.AvrLibrary(
    'kbd',
    source=[
        'KbdController.cpp',
        'Keyboard.cpp',
    ],
    headers=[
        'KbdController.h',
        'KbdDiodeImpl.h',
        'KbdDiodeImpl-defs.h',
        'Keyboard.h',
    ],
    deps=['..:log', '..:util', '..:usb_dbg', '..:usb', '..:usb_kbd'],
)
