#!/usr/bin/python3 -tt
#
# Copyright (c) 2013, Adam Simpkins
#

#
# Values for bmRequestType
#
ENDPOINT_IN = 0x80
ENDPOINT_OUT = 0x00

REQUEST_TYPE_STANDARD = 0x00
REQUEST_TYPE_CLASS = 0x20
REQUEST_TYPE_VENDOR = 0x40

RECIPIENT_DEVICE = 0x00
RECIPIENT_INTERFACE = 0x01
RECIPIENT_ENDPOINT = 0x02
RECIPIENT_OTHER = 0x03

#
# Standard values for bRequest
# (When the type in bmRequestType is REQUEST_TYPE_STANDARD)
#
REQ_GET_STATUS = 0
REQ_CLEAR_FEATURE = 1
REQ_SET_FEATURE = 3
REQ_SET_ADDRESS = 5
REQ_GET_DESCRIPTOR = 6
REQ_SET_DESCRIPTOR = 7
REQ_GET_CONFIGURATION = 8
REQ_SET_CONFIGURATION = 9
REQ_GET_INTERFACE = 10
REQ_SET_INTERFACE = 11
REQ_SYNCH_FRAME = 12

#
# Descriptor types
#
DESC_DEVICE = 1
DESC_CONFIGURATION = 2
DESC_STRING = 3
DESC_INTERFACE = 4
DESC_ENDPOINT = 5
DESC_DEVICE_QUALIFIER = 6
DESC_OTHER_SPEED_CONFIGURATION = 7
DESC_INTERFACE_POWER = 8

CLASS_HID = 3
